---
name: Test Rails
'on': push
jobs:
  Bundle_Install_-2-7_-_ubuntu-latest-:
    name: Bundle Install (2.7 / ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: bundle install
    env:
      REDIS_DRIVER: ruby
  activesupport_-2-7_-_ubuntu-latest-:
    name: activesupport (2.7 / ubuntu-latest)
    runs-on: ubuntu-latest
    needs: Bundle_Install_-2-7_-_ubuntu-latest-
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: bundle install
    - run: bundle exec rake test
      working-directory: activesupport
    services:
      memcached:
        image: memcached:latest
        ports:
        - 11211:11211
        options: --health-cmd "timeout 5 bash -c 'cat < /dev/null > /dev/udp/127.0.0.1/11211'"
          --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout
          5s --health-retries 5
    env:
      REDIS_DRIVER: ruby
  activesupport_isolated_-2-7_-_ubuntu-latest-:
    name: activesupport isolated (2.7 / ubuntu-latest)
    runs-on: ubuntu-latest
    needs: Bundle_Install_-2-7_-_ubuntu-latest-
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: bundle install
    - run: bundle exec rake test:isolated
      working-directory: activesupport
    services:
      memcached:
        image: memcached:latest
        ports:
        - 11211:11211
        options: --health-cmd "timeout 5 bash -c 'cat < /dev/null > /dev/udp/127.0.0.1/11211'"
          --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout
          5s --health-retries 5
    env:
      REDIS_DRIVER: ruby
  actioncable_-2-7_-_ubuntu-latest-:
    name: actioncable (2.7 / ubuntu-latest)
    runs-on: ubuntu-latest
    needs: Bundle_Install_-2-7_-_ubuntu-latest-
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: bundle install
    - run: bundle exec rake test
      working-directory: actioncable
    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout
          5s --health-retries 5
    env:
      REDIS_DRIVER: ruby
  actionmailbox_-2-7_-_ubuntu-latest-:
    name: actionmailbox (2.7 / ubuntu-latest)
    runs-on: ubuntu-latest
    needs: Bundle_Install_-2-7_-_ubuntu-latest-
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: bundle install
    - run: bundle exec rake test
      working-directory: actionmailbox
  actionmailer_-2-7_-_ubuntu-latest-:
    name: actionmailer (2.7 / ubuntu-latest)
    runs-on: ubuntu-latest
    needs: Bundle_Install_-2-7_-_ubuntu-latest-
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: bundle install
    - run: bundle exec rake test
      working-directory: actionmailer
  actionmailer_isolated_-2-7_-_ubuntu-latest-:
    name: actionmailer isolated (2.7 / ubuntu-latest)
    runs-on: ubuntu-latest
    needs: Bundle_Install_-2-7_-_ubuntu-latest-
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: bundle install
    - run: bundle exec rake test:isolated
      working-directory: actionmailer
  actionpack_-2-7_-_ubuntu-latest-:
    name: actionpack (2.7 / ubuntu-latest)
    runs-on: ubuntu-latest
    needs: Bundle_Install_-2-7_-_ubuntu-latest-
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: bundle install
    - run: bundle exec rake test
      working-directory: actionpack
    services:
      memcached:
        image: memcached:latest
        ports:
        - 11211:11211
        options: --health-cmd "timeout 5 bash -c 'cat < /dev/null > /dev/udp/127.0.0.1/11211'"
          --health-interval 10s --health-timeout 5s --health-retries 5
  actionpack_isolated_-2-7_-_ubuntu-latest-:
    name: actionpack isolated (2.7 / ubuntu-latest)
    runs-on: ubuntu-latest
    needs: Bundle_Install_-2-7_-_ubuntu-latest-
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: bundle install
    - run: bundle exec rake test:isolated
      working-directory: actionpack
    services:
      memcached:
        image: memcached:latest
        ports:
        - 11211:11211
        options: --health-cmd "timeout 5 bash -c 'cat < /dev/null > /dev/udp/127.0.0.1/11211'"
          --health-interval 10s --health-timeout 5s --health-retries 5
  actiontext_-2-7_-_ubuntu-latest-:
    name: actiontext (2.7 / ubuntu-latest)
    runs-on: ubuntu-latest
    needs: Bundle_Install_-2-7_-_ubuntu-latest-
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: bundle install
    - run: bundle exec rake test
      working-directory: actiontext
  actionview_-2-7_-_ubuntu-latest-:
    name: actionview (2.7 / ubuntu-latest)
    runs-on: ubuntu-latest
    needs: Bundle_Install_-2-7_-_ubuntu-latest-
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: bundle install
    - run: bundle exec rake test
      working-directory: actionview
  actionview_isolated_-2-7_-_ubuntu-latest-:
    name: actionview isolated (2.7 / ubuntu-latest)
    runs-on: ubuntu-latest
    needs: Bundle_Install_-2-7_-_ubuntu-latest-
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: bundle install
    - run: bundle exec rake test:isolated
      working-directory: actionview
  activejob_-2-7_-_ubuntu-latest-:
    name: activejob (2.7 / ubuntu-latest)
    runs-on: ubuntu-latest
    needs: Bundle_Install_-2-7_-_ubuntu-latest-
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: bundle install
    - run: bundle exec rake test
      working-directory: activejob
  activejob_isolated_-2-7_-_ubuntu-latest-:
    name: activejob isolated (2.7 / ubuntu-latest)
    runs-on: ubuntu-latest
    needs: Bundle_Install_-2-7_-_ubuntu-latest-
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: bundle install
    - run: bundle exec rake test:isolated
      working-directory: activejob
  activemodel_-2-7_-_ubuntu-latest-:
    name: activemodel (2.7 / ubuntu-latest)
    runs-on: ubuntu-latest
    needs: Bundle_Install_-2-7_-_ubuntu-latest-
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: bundle install
    - run: bundle exec rake test
      working-directory: activemodel
  activemodel_isolated_-2-7_-_ubuntu-latest-:
    name: activemodel isolated (2.7 / ubuntu-latest)
    runs-on: ubuntu-latest
    needs: Bundle_Install_-2-7_-_ubuntu-latest-
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: bundle install
    - run: bundle exec rake test:isolated
      working-directory: activemodel
  activerecord_mysql2_-2-7_-_ubuntu-latest-:
    name: activerecord mysql2 (2.7 / ubuntu-latest)
    runs-on: ubuntu-latest
    needs: Bundle_Install_-2-7_-_ubuntu-latest-
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: bundle install
    - run: sudo apt-get update
    - run: sudo apt-get install -y --no-install-recommends default-libmysqlclient-dev
        default-mysql-client
    - run: |-
        mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "create user rails@'%';grant all privileges on activerecord_unittest.* to rails@'%';grant all privileges on activerecord_unittest2.* to rails@'%';grant all privileges on inexistent_activerecord_unittest.* to rails@'%';create database activerecord_unittest default character set utf8mb4;create database activerecord_unittest2 default character set utf8mb4;
                "
    - run: bundle exec rake db:mysql:rebuild mysql2:test
      working-directory: activerecord
    services:
      mysql:
        image: mysql:latest
        ports:
        - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s
          --health-retries=3
    env:
      MYSQL_HOST: 127.0.0.1
  activerecord_mysql2-isolated_-2-7_-_ubuntu-latest-:
    name: activerecord mysql2:isolated (2.7 / ubuntu-latest)
    runs-on: ubuntu-latest
    needs: Bundle_Install_-2-7_-_ubuntu-latest-
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: bundle install
    - run: sudo apt-get update
    - run: sudo apt-get install -y --no-install-recommends default-libmysqlclient-dev
        default-mysql-client
    - run: |-
        mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "create user rails@'%';grant all privileges on activerecord_unittest.* to rails@'%';grant all privileges on activerecord_unittest2.* to rails@'%';grant all privileges on inexistent_activerecord_unittest.* to rails@'%';create database activerecord_unittest default character set utf8mb4;create database activerecord_unittest2 default character set utf8mb4;
                "
    - run: bundle exec rake db:mysql:rebuild mysql2:isolated_test
      working-directory: activerecord
    services:
      mysql:
        image: mysql:latest
        ports:
        - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s
          --health-retries=3
    env:
      MYSQL_HOST: 127.0.0.1
  activerecord_postgresql_-2-7_-_ubuntu-latest-:
    name: activerecord postgresql (2.7 / ubuntu-latest)
    runs-on: ubuntu-latest
    needs: Bundle_Install_-2-7_-_ubuntu-latest-
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: bundle install
    - run: sudo apt-get update
    - run: sudo apt-get install -y --no-install-recommends postgresql-client
    - run: bundle exec rake db:postgresql:rebuild postgresql:test
      working-directory: activerecord
    services:
      postgres:
        image: postgres
        ports:
        - 5432:5432
        options: "--health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5"
        env:
          POSTGRES_PASSWORD: postgres
    env:
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: postgres
  activerecord_postgresql-isolated_-2-7_-_ubuntu-latest-:
    name: activerecord postgresql:isolated (2.7 / ubuntu-latest)
    runs-on: ubuntu-latest
    needs: Bundle_Install_-2-7_-_ubuntu-latest-
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: bundle install
    - run: sudo apt-get update
    - run: sudo apt-get install -y --no-install-recommends postgresql-client
    - run: bundle exec rake db:postgresql:rebuild postgresql:isolated_test
      working-directory: activerecord
    services:
      postgres:
        image: postgres
        ports:
        - 5432:5432
        options: "--health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5"
        env:
          POSTGRES_PASSWORD: postgres
    env:
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: postgres
  activerecord_sqlite3_-2-7_-_ubuntu-latest-:
    name: activerecord sqlite3 (2.7 / ubuntu-latest)
    runs-on: ubuntu-latest
    needs: Bundle_Install_-2-7_-_ubuntu-latest-
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: bundle install
    - run: sudo apt-get update
    - run: sudo apt-get install -y --no-install-recommends sqlite3
    - run: bundle exec rake sqlite3:test
      working-directory: activerecord
  activerecord_sqlite3-isolated_-2-7_-_ubuntu-latest-:
    name: activerecord sqlite3:isolated (2.7 / ubuntu-latest)
    runs-on: ubuntu-latest
    needs: Bundle_Install_-2-7_-_ubuntu-latest-
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: bundle install
    - run: sudo apt-get update
    - run: sudo apt-get install -y --no-install-recommends sqlite3
    - run: bundle exec rake sqlite3:isolated_test
      working-directory: activerecord
